package com.mobiletreeplantingapp.ui.util

import com.google.firebase.firestore.FirebaseFirestore
import com.mobiletreeplantingapp.data.model.TreeRecommendationData
import kotlinx.coroutines.tasks.await
import java.util.UUID

object TreeRecommendationSeeder {
    private val firestore = FirebaseFirestore.getInstance()
    private val recommendationsCollection = firestore.collection("tree_recommendations")

    suspend fun seedTreeRecommendations() {
        val recommendations = listOf(
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Acacia",
                description = "Native to Africa, excellent for arid and semi-arid regions. Provides good shade and helps in soil nitrogen fixation.",
                growthRate = "Medium to Fast",
                maintainanceLevel = "Low",
                soilPreference = "Sandy to Clay",
                climatePreference = "Tropical to Semi-arid",
                minElevation = 0.0,
                maxElevation = 2000.0,
                suitableSoilTypes = listOf("sandy", "clay", "loamy"),
                suitableClimateZones = listOf("tropical", "semi-arid"),
                waterRequirement = "low",
                suitabilityScore = 0.95f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Grevillea Robusta (Silky Oak)",
                description = "Fast-growing timber tree, good for windbreaks and soil conservation. Popular in agroforestry.",
                growthRate = "Fast",
                maintainanceLevel = "Low",
                soilPreference = "Well-drained, acidic to neutral",
                climatePreference = "Tropical Highland",
                minElevation = 500.0,
                maxElevation = 2300.0,
                suitableSoilTypes = listOf("loamy", "sandy"),
                suitableClimateZones = listOf("tropical", "subtropical"),
                waterRequirement = "medium",
                suitabilityScore = 0.9f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Eucalyptus",
                description = "Fast-growing tree excellent for timber and poles. Good for higher altitude areas.",
                growthRate = "Very Fast",
                maintainanceLevel = "Low",
                soilPreference = "Well-drained, various types",
                climatePreference = "Tropical Highland",
                minElevation = 1000.0,
                maxElevation = 2500.0,
                suitableSoilTypes = listOf("sandy", "loamy", "clay"),
                suitableClimateZones = listOf("tropical", "subtropical"),
                waterRequirement = "medium",
                suitabilityScore = 0.85f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Markhamia Lutea",
                description = "Indigenous tree good for timber and soil conservation. Excellent for agroforestry.",
                growthRate = "Medium",
                maintainanceLevel = "Low",
                soilPreference = "Well-drained soils",
                climatePreference = "Tropical Highland",
                minElevation = 1000.0,
                maxElevation = 2000.0,
                suitableSoilTypes = listOf("loamy", "clay"),
                suitableClimateZones = listOf("tropical"),
                waterRequirement = "medium",
                suitabilityScore = 0.88f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Croton Megalocarpus",
                description = "Native tree good for shade and soil improvement. Popular in coffee growing areas.",
                growthRate = "Medium",
                maintainanceLevel = "Low",
                soilPreference = "Various soil types",
                climatePreference = "Tropical Highland",
                minElevation = 900.0,
                maxElevation = 2100.0,
                suitableSoilTypes = listOf("loamy", "clay", "sandy"),
                suitableClimateZones = listOf("tropical"),
                waterRequirement = "medium",
                suitabilityScore = 0.87f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Melia Volkensii",
                description = "Drought-resistant tree with valuable timber. Excellent for semi-arid areas.",
                growthRate = "Fast",
                maintainanceLevel = "Low",
                soilPreference = "Well-drained soils",
                climatePreference = "Semi-arid",
                minElevation = 0.0,
                maxElevation = 1600.0,
                suitableSoilTypes = listOf("sandy", "loamy"),
                suitableClimateZones = listOf("semi-arid"),
                waterRequirement = "low",
                suitabilityScore = 0.92f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Prunus Africana",
                description = "Indigenous medicinal tree. Good for high rainfall areas and forest restoration.",
                growthRate = "Slow",
                maintainanceLevel = "Medium",
                soilPreference = "Rich, well-drained soils",
                climatePreference = "Tropical Highland",
                minElevation = 1500.0,
                maxElevation = 3000.0,
                suitableSoilTypes = listOf("loamy"),
                suitableClimateZones = listOf("tropical"),
                waterRequirement = "high",
                suitabilityScore = 0.83f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Casuarina",
                description = "Fast-growing tree good for windbreaks and coastal areas. Tolerates saline soils.",
                growthRate = "Fast",
                maintainanceLevel = "Low",
                soilPreference = "Sandy to loamy",
                climatePreference = "Coastal to Semi-arid",
                minElevation = 0.0,
                maxElevation = 1500.0,
                suitableSoilTypes = listOf("sandy", "loamy"),
                suitableClimateZones = listOf("coastal", "semi-arid"),
                waterRequirement = "low",
                suitabilityScore = 0.89f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Moringa Oleifera",
                description = "Fast-growing nutritious tree. Good for arid areas and has multiple uses.",
                growthRate = "Very Fast",
                maintainanceLevel = "Low",
                soilPreference = "Well-drained, sandy to loamy",
                climatePreference = "Tropical to Semi-arid",
                minElevation = 0.0,
                maxElevation = 1200.0,
                suitableSoilTypes = listOf("sandy", "loamy"),
                suitableClimateZones = listOf("tropical", "semi-arid"),
                waterRequirement = "low",
                suitabilityScore = 0.91f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Warburgia Ugandensis",
                description = "Indigenous medicinal tree. Good for medium to high altitude areas.",
                growthRate = "Medium",
                maintainanceLevel = "Medium",
                soilPreference = "Well-drained soils",
                climatePreference = "Tropical Highland",
                minElevation = 1200.0,
                maxElevation = 2200.0,
                suitableSoilTypes = listOf("loamy", "clay"),
                suitableClimateZones = listOf("tropical"),
                waterRequirement = "medium",
                suitabilityScore = 0.86f
            ),
            // Added 20+ new tree recommendations below
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Azadirachta Indica (Neem)",
                description = "Versatile medicinal tree with insecticidal properties. Excellent for hot, dry regions and urban planting.",
                growthRate = "Fast",
                maintainanceLevel = "Low",
                soilPreference = "Adaptable to most soils",
                climatePreference = "Tropical to Semi-arid",
                minElevation = 0.0,
                maxElevation = 1500.0,
                suitableSoilTypes = listOf("sandy", "loamy", "clay"),
                suitableClimateZones = listOf("tropical", "semi-arid"),
                waterRequirement = "low",
                suitabilityScore = 0.93f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Tamarindus Indica",
                description = "Drought-resistant multipurpose tree. Produces edible fruits and provides excellent shade.",
                growthRate = "Slow to Medium",
                maintainanceLevel = "Low",
                soilPreference = "Deep, well-drained soils",
                climatePreference = "Tropical to Semi-arid",
                minElevation = 0.0,
                maxElevation = 1500.0,
                suitableSoilTypes = listOf("sandy", "loamy", "clay"),
                suitableClimateZones = listOf("tropical", "semi-arid"),
                waterRequirement = "low",
                suitabilityScore = 0.88f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Tectona Grandis (Teak)",
                description = "Valuable timber tree with excellent wood quality. Good for commercial forestry.",
                growthRate = "Medium",
                maintainanceLevel = "Medium",
                soilPreference = "Deep, well-drained, fertile soils",
                climatePreference = "Tropical Moist",
                minElevation = 0.0,
                maxElevation = 1200.0,
                suitableSoilTypes = listOf("loamy", "clay"),
                suitableClimateZones = listOf("tropical"),
                waterRequirement = "medium",
                suitabilityScore = 0.87f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Mangifera Indica (Mango)",
                description = "Popular fruit tree with deep roots good for soil stabilization. Provides good shade and economic benefits.",
                growthRate = "Medium",
                maintainanceLevel = "Medium",
                soilPreference = "Well-drained, deep soils",
                climatePreference = "Tropical to Subtropical",
                minElevation = 0.0,
                maxElevation = 1200.0,
                suitableSoilTypes = listOf("loamy", "sandy"),
                suitableClimateZones = listOf("tropical", "subtropical"),
                waterRequirement = "medium",
                suitabilityScore = 0.85f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Bambusa Vulgaris (Bamboo)",
                description = "Fast-growing woody grass excellent for erosion control and quick biomass production.",
                growthRate = "Very Fast",
                maintainanceLevel = "Low",
                soilPreference = "Moist, well-drained soils",
                climatePreference = "Tropical to Subtropical",
                minElevation = 0.0,
                maxElevation = 1500.0,
                suitableSoilTypes = listOf("loamy", "sandy"),
                suitableClimateZones = listOf("tropical", "subtropical"),
                waterRequirement = "medium",
                suitabilityScore = 0.89f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Khaya Senegalensis (African Mahogany)",
                description = "High-value timber tree good for afforestation and urban planting. Provides excellent shade.",
                growthRate = "Medium",
                maintainanceLevel = "Medium",
                soilPreference = "Deep, well-drained soils",
                climatePreference = "Tropical",
                minElevation = 0.0,
                maxElevation = 1500.0,
                suitableSoilTypes = listOf("loamy", "clay"),
                suitableClimateZones = listOf("tropical", "subtropical"),
                waterRequirement = "medium",
                suitabilityScore = 0.84f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Leucaena Leucocephala",
                description = "Fast-growing nitrogen-fixing tree excellent for agroforestry and soil improvement.",
                growthRate = "Very Fast",
                maintainanceLevel = "Low",
                soilPreference = "Adaptable to most soils",
                climatePreference = "Tropical to Subtropical",
                minElevation = 0.0,
                maxElevation = 1800.0,
                suitableSoilTypes = listOf("sandy", "loamy", "clay"),
                suitableClimateZones = listOf("tropical", "subtropical"),
                waterRequirement = "low",
                suitabilityScore = 0.9f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Faidherbia Albida",
                description = "Nitrogen-fixing tree with reverse leaf phenology. Excellent for agroforestry in semi-arid regions.",
                growthRate = "Medium",
                maintainanceLevel = "Low",
                soilPreference = "Sandy to loamy soils",
                climatePreference = "Semi-arid",
                minElevation = 0.0,
                maxElevation = 2000.0,
                suitableSoilTypes = listOf("sandy", "loamy"),
                suitableClimateZones = listOf("semi-arid"),
                waterRequirement = "low",
                suitabilityScore = 0.91f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Olea Europaea (African Wild Olive)",
                description = "Drought-resistant indigenous tree good for highlands. Long-lived with excellent wood quality.",
                growthRate = "Slow",
                maintainanceLevel = "Low",
                soilPreference = "Well-drained soils",
                climatePreference = "Tropical Highland",
                minElevation = 1200.0,
                maxElevation = 2800.0,
                suitableSoilTypes = listOf("loamy", "rocky"),
                suitableClimateZones = listOf("highland", "mediterranean"),
                waterRequirement = "low",
                suitabilityScore = 0.82f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Syzygium Cumini (Java Plum)",
                description = "Sturdy evergreen tree with edible fruits. Good for riverine areas and shade.",
                growthRate = "Medium",
                maintainanceLevel = "Low",
                soilPreference = "Moist, well-drained soils",
                climatePreference = "Tropical to Subtropical",
                minElevation = 0.0,
                maxElevation = 1800.0,
                suitableSoilTypes = listOf("loamy", "clay", "sandy"),
                suitableClimateZones = listOf("tropical", "subtropical"),
                waterRequirement = "medium",
                suitabilityScore = 0.83f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Calliandra Calothyrsus",
                description = "Fast-growing nitrogen-fixing tree excellent for fodder, firewood, and soil improvement.",
                growthRate = "Fast",
                maintainanceLevel = "Low",
                soilPreference = "Adaptable to most soils",
                climatePreference = "Tropical Highland",
                minElevation = 500.0,
                maxElevation = 2000.0,
                suitableSoilTypes = listOf("loamy", "clay", "sandy"),
                suitableClimateZones = listOf("tropical"),
                waterRequirement = "medium",
                suitabilityScore = 0.88f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Terminalia Brownii",
                description = "Indigenous drought-resistant tree with medicinal properties. Good for semi-arid areas.",
                growthRate = "Medium",
                maintainanceLevel = "Low",
                soilPreference = "Well-drained soils",
                climatePreference = "Semi-arid",
                minElevation = 0.0,
                maxElevation = 1800.0,
                suitableSoilTypes = listOf("sandy", "loamy"),
                suitableClimateZones = listOf("semi-arid"),
                waterRequirement = "low",
                suitabilityScore = 0.89f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Persea Americana (Avocado)",
                description = "Economically valuable fruit tree. Good for highland areas with adequate rainfall.",
                growthRate = "Medium",
                maintainanceLevel = "Medium",
                soilPreference = "Deep, well-drained soils",
                climatePreference = "Tropical Highland",
                minElevation = 800.0,
                maxElevation = 2000.0,
                suitableSoilTypes = listOf("loamy"),
                suitableClimateZones = listOf("tropical", "subtropical"),
                waterRequirement = "medium",
                suitabilityScore = 0.84f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Dalbergia Melanoxylon (African Blackwood)",
                description = "Slow-growing hardwood tree valued for timber and musical instruments. Drought-resistant.",
                growthRate = "Slow",
                maintainanceLevel = "Low",
                soilPreference = "Well-drained soils",
                climatePreference = "Semi-arid to Subtropical",
                minElevation = 0.0,
                maxElevation = 1500.0,
                suitableSoilTypes = listOf("sandy", "loamy"),
                suitableClimateZones = listOf("semi-arid", "subtropical"),
                waterRequirement = "low",
                suitabilityScore = 0.81f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Balanites Aegyptiaca (Desert Date)",
                description = "Highly drought-resistant tree with multiple uses including food, fodder, and medicine.",
                growthRate = "Slow",
                maintainanceLevel = "Low",
                soilPreference = "Sandy to clay soils",
                climatePreference = "Arid to Semi-arid",
                minElevation = 0.0,
                maxElevation = 1600.0,
                suitableSoilTypes = listOf("sandy", "clay"),
                suitableClimateZones = listOf("arid", "semi-arid"),
                waterRequirement = "very low",
                suitabilityScore = 0.9f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Albizia Lebbeck (Siris Tree)",
                description = "Fast-growing nitrogen-fixing tree good for shade, soil improvement, and fodder.",
                growthRate = "Fast",
                maintainanceLevel = "Low",
                soilPreference = "Adaptable to most soils",
                climatePreference = "Tropical to Subtropical",
                minElevation = 0.0,
                maxElevation = 1800.0,
                suitableSoilTypes = listOf("sandy", "loamy", "clay"),
                suitableClimateZones = listOf("tropical", "subtropical"),
                waterRequirement = "low",
                suitabilityScore = 0.86f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Juniperus Procera (African Pencil Cedar)",
                description = "Indigenous conifer good for high-altitude areas. Valuable timber and traditional medicine.",
                growthRate = "Slow",
                maintainanceLevel = "Low",
                soilPreference = "Well-drained soils",
                climatePreference = "Tropical Highland",
                minElevation = 1500.0,
                maxElevation = 3000.0,
                suitableSoilTypes = listOf("loamy", "rocky"),
                suitableClimateZones = listOf("highland"),
                waterRequirement = "low",
                suitabilityScore = 0.82f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Senna Siamea",
                description = "Fast-growing multipurpose tree good for fuelwood, posts, and shade. Adapts to various conditions.",
                growthRate = "Fast",
                maintainanceLevel = "Low",
                soilPreference = "Adaptable to poor soils",
                climatePreference = "Tropical",
                minElevation = 0.0,
                maxElevation = 1500.0,
                suitableSoilTypes = listOf("sandy", "loamy", "clay"),
                suitableClimateZones = listOf("tropical"),
                waterRequirement = "low",
                suitabilityScore = 0.87f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Cordia Africana",
                description = "Indigenous multipurpose tree valued for timber and fruit. Popular in agroforestry systems.",
                growthRate = "Medium",
                maintainanceLevel = "Low",
                soilPreference = "Well-drained soils",
                climatePreference = "Tropical Highland",
                minElevation = 1000.0,
                maxElevation = 2500.0,
                suitableSoilTypes = listOf("loamy", "clay"),
                suitableClimateZones = listOf("tropical"),
                waterRequirement = "medium",
                suitabilityScore = 0.85f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Citrus Sinensis (Orange)",
                description = "Popular fruit tree with commercial value. Good for medium altitude areas with proper management.",
                growthRate = "Medium",
                maintainanceLevel = "High",
                soilPreference = "Well-drained, fertile soils",
                climatePreference = "Subtropical to Tropical Highland",
                minElevation = 800.0,
                maxElevation = 2000.0,
                suitableSoilTypes = listOf("loamy", "sandy"),
                suitableClimateZones = listOf("subtropical", "tropical"),
                waterRequirement = "medium",
                suitabilityScore = 0.8f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Gliricidia Sepium",
                description = "Fast-growing nitrogen-fixing tree excellent for live fencing, fodder, and soil improvement.",
                growthRate = "Fast",
                maintainanceLevel = "Low",
                soilPreference = "Adaptable to most soils",
                climatePreference = "Tropical",
                minElevation = 0.0,
                maxElevation = 1200.0,
                suitableSoilTypes = listOf("sandy", "loamy", "clay"),
                suitableClimateZones = listOf("tropical"),
                waterRequirement = "low",
                suitabilityScore = 0.87f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Podocarpus Falcatus",
                description = "Indigenous conifer with valuable timber. Good for high altitude conservation areas.",
                growthRate = "Slow",
                maintainanceLevel = "Low",
                soilPreference = "Well-drained soils",
                climatePreference = "Tropical Highland",
                minElevation = 1500.0,
                maxElevation = 2800.0,
                suitableSoilTypes = listOf("loamy"),
                suitableClimateZones = listOf("highland"),
                waterRequirement = "medium",
                suitabilityScore = 0.81f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Dovyalis Caffra (Kei Apple)",
                description = "Indigenous thorny shrub or small tree good for hedges and producing edible fruits.",
                growthRate = "Medium",
                maintainanceLevel = "Low",
                soilPreference = "Well-drained soils",
                climatePreference = "Subtropical to Semi-arid",
                minElevation = 0.0,
                maxElevation = 1800.0,
                suitableSoilTypes = listOf("sandy", "loamy"),
                suitableClimateZones = listOf("subtropical", "semi-arid"),
                waterRequirement = "low",
                suitabilityScore = 0.83f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Sesbania Sesban",
                description = "Fast-growing nitrogen-fixing small tree good for improved fallows and soil reclamation.",
                growthRate = "Very Fast",
                maintainanceLevel = "Low",
                soilPreference = "Adaptable to most soils, tolerates waterlogging",
                climatePreference = "Tropical to Subtropical",
                minElevation = 0.0,
                maxElevation = 2000.0,
                suitableSoilTypes = listOf("sandy", "loamy", "clay"),
                suitableClimateZones = listOf("tropical", "subtropical"),
                waterRequirement = "medium",
                suitabilityScore = 0.87f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Hagenia Abyssinica",
                description = "Indigenous medicinal tree good for highland areas and watershed protection.",
                growthRate = "Medium",
                maintainanceLevel = "Low",
                soilPreference = "Well-drained, fertile soils",
                climatePreference = "Tropical Highland",
                minElevation = 2000.0,
                maxElevation = 3500.0,
                suitableSoilTypes = listOf("loamy"),
                suitableClimateZones = listOf("highland"),
                waterRequirement = "medium",
                suitabilityScore = 0.82f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Vitex Keniensis (Meru Oak)",
                description = "Indigenous hardwood tree with valuable timber. Good for medium to high altitude areas.",
                growthRate = "Medium",
                maintainanceLevel = "Low",
                soilPreference = "Well-drained, fertile soils",
                climatePreference = "Tropical Highland",
                minElevation = 1200.0,
                maxElevation = 2400.0,
                suitableSoilTypes = listOf("loamy", "clay"),
                suitableClimateZones = listOf("tropical"),
                waterRequirement = "medium",
                suitabilityScore = 0.84f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Ziziphus Mauritiana (Indian Jujube)",
                description = "Drought-hardy tree with edible fruits. Good for arid and semi-arid regions.",
                growthRate = "Medium",
                maintainanceLevel = "Low",
                soilPreference = "Adaptable to most soils",
                climatePreference = "Semi-arid to Tropical",
                minElevation = 0.0,
                maxElevation = 1500.0,
                suitableSoilTypes = listOf("sandy", "loamy", "clay"),
                suitableClimateZones = listOf("semi-arid", "tropical"),
                waterRequirement = "low",
                suitabilityScore = 0.86f
            ),
            // Add these new recommendations after the existing ones
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Pinus Patula (Mexican Weeping Pine)",
                description = "Fast-growing conifer ideal for commercial forestry and high-altitude areas.",
                growthRate = "Fast",
                maintainanceLevel = "Low",
                soilPreference = "Well-drained, acidic soils",
                climatePreference = "Highland",
                minElevation = 1500.0,
                maxElevation = 3000.0,
                suitableSoilTypes = listOf("loamy", "sandy"),
                suitableClimateZones = listOf("highland", "temperate"),
                waterRequirement = "medium",
                suitabilityScore = 0.88f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Macadamia Integrifolia",
                description = "Commercial nut tree well-suited for highland areas with good economic returns.",
                growthRate = "Slow",
                maintainanceLevel = "High",
                soilPreference = "Deep, well-drained, fertile soils",
                climatePreference = "Tropical Highland",
                minElevation = 1000.0,
                maxElevation = 2100.0,
                suitableSoilTypes = listOf("loamy", "volcanic"),
                suitableClimateZones = listOf("tropical highland"),
                waterRequirement = "medium",
                suitabilityScore = 0.85f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Afrocarpus Gracilior",
                description = "Indigenous highland conifer valuable for timber and environmental conservation.",
                growthRate = "Slow",
                maintainanceLevel = "Low",
                soilPreference = "Deep, well-drained soils",
                climatePreference = "Highland Forest",
                minElevation = 1800.0,
                maxElevation = 2800.0,
                suitableSoilTypes = listOf("loamy", "clay"),
                suitableClimateZones = listOf("highland"),
                waterRequirement = "high",
                suitabilityScore = 0.83f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Parkinsonia Aculeata",
                description = "Drought-resistant thorny tree excellent for desert revegetation and livestock shade.",
                growthRate = "Fast",
                maintainanceLevel = "Very Low",
                soilPreference = "Sandy to saline soils",
                climatePreference = "Arid",
                minElevation = 0.0,
                maxElevation = 1000.0,
                suitableSoilTypes = listOf("sandy", "saline"),
                suitableClimateZones = listOf("arid", "semi-arid"),
                waterRequirement = "very low",
                suitabilityScore = 0.92f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Spathodea Campanulata",
                description = "African Tulip Tree, ornamental with bright flowers, good for urban landscapes.",
                growthRate = "Fast",
                maintainanceLevel = "Medium",
                soilPreference = "Moist, well-drained soils",
                climatePreference = "Tropical Lowland",
                minElevation = 0.0,
                maxElevation = 1200.0,
                suitableSoilTypes = listOf("loamy", "clay"),
                suitableClimateZones = listOf("tropical"),
                waterRequirement = "high",
                suitabilityScore = 0.81f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Commiphora Africana",
                description = "Indigenous drought-resistant tree good for myrrh production and live fencing.",
                growthRate = "Slow",
                maintainanceLevel = "Very Low",
                soilPreference = "Rocky, sandy soils",
                climatePreference = "Arid to Semi-arid",
                minElevation = 0.0,
                maxElevation = 1500.0,
                suitableSoilTypes = listOf("rocky", "sandy"),
                suitableClimateZones = listOf("arid", "semi-arid"),
                waterRequirement = "very low",
                suitabilityScore = 0.89f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Alnus Acuminata",
                description = "Fast-growing highland tree good for soil improvement and riverbank protection.",
                growthRate = "Fast",
                maintainanceLevel = "Low",
                soilPreference = "Moist, well-drained soils",
                climatePreference = "Highland",
                minElevation = 1800.0,
                maxElevation = 3200.0,
                suitableSoilTypes = listOf("loamy", "alluvial"),
                suitableClimateZones = listOf("highland"),
                waterRequirement = "high",
                suitabilityScore = 0.86f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Ceiba Pentandra (Kapok)",
                description = "Giant rainforest tree with ecological value for wildlife. Good for urban shade.",
                growthRate = "Fast",
                maintainanceLevel = "Low",
                soilPreference = "Deep, well-drained soils",
                climatePreference = "Tropical Lowland",
                minElevation = 0.0,
                maxElevation = 1000.0,
                suitableSoilTypes = listOf("loamy", "clay"),
                suitableClimateZones = listOf("tropical"),
                waterRequirement = "high",
                suitabilityScore = 0.84f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Handroanthus Impetiginosus (Pink Trumpet)",
                description = "Beautiful flowering tree good for urban landscaping and avenue planting.",
                growthRate = "Medium",
                maintainanceLevel = "Medium",
                soilPreference = "Well-drained soils",
                climatePreference = "Tropical to Subtropical",
                minElevation = 0.0,
                maxElevation = 1500.0,
                suitableSoilTypes = listOf("loamy", "sandy"),
                suitableClimateZones = listOf("tropical", "subtropical"),
                waterRequirement = "medium",
                suitabilityScore = 0.82f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Prosopis Juliflora",
                description = "Highly drought-resistant tree for extreme arid conditions. Good for soil stabilization.",
                growthRate = "Fast",
                maintainanceLevel = "Very Low",
                soilPreference = "Sandy to saline soils",
                climatePreference = "Arid",
                minElevation = 0.0,
                maxElevation = 1000.0,
                suitableSoilTypes = listOf("sandy", "saline"),
                suitableClimateZones = listOf("arid"),
                waterRequirement = "very low",
                suitabilityScore = 0.91f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Artocarpus Heterophyllus (Jackfruit)",
                description = "Large fruit tree with multiple uses. Good for tropical homesteads.",
                growthRate = "Medium",
                maintainanceLevel = "Medium",
                soilPreference = "Deep, well-drained soils",
                climatePreference = "Tropical",
                minElevation = 0.0,
                maxElevation = 1200.0,
                suitableSoilTypes = listOf("loamy", "clay"),
                suitableClimateZones = listOf("tropical"),
                waterRequirement = "medium",
                suitabilityScore = 0.83f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Adansonia Digitata (Baobab)",
                description = "Iconic African tree with multiple uses. Excellent for arid regions.",
                growthRate = "Very Slow",
                maintainanceLevel = "Very Low",
                soilPreference = "Sandy to rocky soils",
                climatePreference = "Semi-arid to Arid",
                minElevation = 0.0,
                maxElevation = 1500.0,
                suitableSoilTypes = listOf("sandy", "rocky"),
                suitableClimateZones = listOf("arid", "semi-arid"),
                waterRequirement = "very low",
                suitabilityScore = 0.94f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Erythrina Abyssinica (Red Hot Poker)",
                description = "Indigenous flowering tree good for soil improvement and bee forage.",
                growthRate = "Fast",
                maintainanceLevel = "Low",
                soilPreference = "Well-drained soils",
                climatePreference = "Tropical Highland",
                minElevation = 1200.0,
                maxElevation = 2400.0,
                suitableSoilTypes = listOf("loamy", "clay"),
                suitableClimateZones = listOf("tropical", "highland"),
                waterRequirement = "medium",
                suitabilityScore = 0.85f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Liquidambar Styraciflua",
                description = "Beautiful ornamental tree with fall colors. Good for urban landscapes.",
                growthRate = "Medium",
                maintainanceLevel = "Medium",
                soilPreference = "Moist, well-drained soils",
                climatePreference = "Highland",
                minElevation = 1500.0,
                maxElevation = 2500.0,
                suitableSoilTypes = listOf("loamy"),
                suitableClimateZones = listOf("highland", "temperate"),
                waterRequirement = "high",
                suitabilityScore = 0.79f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Parkia Biglobosa (African Locust)",
                description = "Valuable food and fodder tree for savanna regions.",
                growthRate = "Medium",
                maintainanceLevel = "Low",
                soilPreference = "Deep, well-drained soils",
                climatePreference = "Savanna",
                minElevation = 0.0,
                maxElevation = 1200.0,
                suitableSoilTypes = listOf("sandy", "loamy"),
                suitableClimateZones = listOf("savanna", "semi-arid"),
                waterRequirement = "low",
                suitabilityScore = 0.88f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Casimiroa Edulis (White Sapote)",
                description = "Fruit tree adapted to subtropical highlands. Good for small-scale farming.",
                growthRate = "Medium",
                maintainanceLevel = "Medium",
                soilPreference = "Well-drained soils",
                climatePreference = "Subtropical Highland",
                minElevation = 1000.0,
                maxElevation = 2200.0,
                suitableSoilTypes = listOf("loamy", "sandy"),
                suitableClimateZones = listOf("subtropical", "highland"),
                waterRequirement = "medium",
                suitabilityScore = 0.81f
            ),
            TreeRecommendationData(
                id = UUID.randomUUID().toString(),
                species = "Stereospermum Kunthianum",
                description = "Drought-resistant flowering tree good for parklands and urban areas.",
                growthRate = "Medium",
                maintainanceLevel = "Low",
                soilPreference = "Various soil types",
                climatePreference = "Semi-arid to Savanna",
                minElevation = 0.0,
                maxElevation = 1800.0,
                suitableSoilTypes = listOf("sandy", "rocky", "loamy"),
                suitableClimateZones = listOf("semi-arid", "savanna"),
                waterRequirement = "low",
                suitabilityScore = 0.87f
            )
        )

        recommendations.forEach { recommendation ->
            try {
                recommendationsCollection
                    .document(recommendation.id)
                    .set(recommendation)
                    .await()
                println("Successfully added recommendation for: ${recommendation.species}")
            } catch (e: Exception) {
                println("Error adding recommendation for ${recommendation.species}: ${e.message}")
            }
        }
    }
}